apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gz0wc4f52-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gz0wc4f52-go 
  name: gz0wc4f52-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gz0wc4f52-go 
